# 通常は1
scheme = 1

# カーソルフォルダを置いているフォルダ　通常は変更する必要なし
path = '''C:\Windows\Cursors'''

# カーソルが入っているフォルダ名
name = ""

# cursor_name = "" # フォルダ名とカーソル名を別にしたい場合

# カーソルファイルの名前
arrow       = "" # 「通常の選択」
help        = "" # 「ヘルプの選択」
appstarting = "" # 「バックグラウンドで作業中」
wait        = "" # 「待ち状態」
crosshair   = "" # 「領域選択」
ibeam       = "" # 「テキスト選択」
nwpen       = "" # 「手書き」
no          = "" # 「利用不可」
sizens      = "" # 「上下に拡大/縮小」
sizewe      = "" # 「左右に拡大/縮小」
sizenwse    = "" # 「斜めに拡大/縮小 1」
sizenesw    = "" # 「斜めに拡大/縮小 2」
sizeall     = "" # 「移動」
uparrow     = "" # 「代替選択」
hand        = "" # 「リンクの選択」